services:
  # -------------------- RABBITMQ -------------------- #
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ protocol
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices-net

  # -------------------- PAYMENT SERVICE -------------------- #
  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: always
    env_file:
      - ./payment-service/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=4002
    ports:
      - "4002:4002"
    networks:
      - microservices-net

# -------------------- NETWORK -------------------- #
networks:
  microservices-net:
    driver: bridge
