# Sử dụng Node.js chính thức
FROM node:20

# Đặt thư mục làm việc
WORKDIR /app

# Copy package.json và package-lock.json (nếu có)
COPY package*.json ./

# Cài dependencies
RUN npm install

# Copy toàn bộ code vào container
COPY . .

# Expose port (nếu app chạy ở 4002)
EXPOSE 4002

# Lệnh chạy app
CMD ["npm", "start"]
